### PR TITLE
Add exclude constraints

### PR DESCRIPTION
**Pull request by ArthurWD**
Thanks for making this repo! I took the liberty to add exclude constraints. Had to restructure some files. Hope you like it!

### CODE REVIEW

**Comment by ArthurWD** [comment]
Just found out that the dump to schema.rb includes creating both the index as the exclude constraint. The latter tries to create the index again which causes an error. I'll add USING INDEX soon to hopefully fix this.

**Comment by ArthurWD** [comment]
It's not possible to use an existing index when creating an exclude constraint, so I made sure indexes of constraints are not dumped to schema.rb. Feels a bit hacky but it works.

Any ideas on the failing tests? It's all green locally.

**Comment by betesh** [comment]
Sorry it took me so long to notice this.

While I familiarize myself with exclude constraints so that I can review this, would you please rebase this onto master?

**Comment by ArthurWD** [comment]
I've rebased the branch on master. The tests seem to randomly fail. Not sure what causes this, but maybe you could first check out the basics of the PR before I dive into the failing tests?

**Comment by betesh** [comment]
Turns out those tests were intermittent on master as well.  #9 seems to have fixed 99% of it, though I did still see one bizarre intermittent failure.  Give it another rebase and let's see what happens.

**Comment by betesh** [comment]
Refactored as #15

**Pull request closed without merging**
